apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: retailstore
spec:
  replicas: 1

  selector:
    matchLabels:
      app: cart

  template:
    metadata:
      labels:
        app: cart

    spec:
      containers:
        - name: cart
          image: xshrp/retailstore-carts:latest

          ports:
            - containerPort: 8080

          env:
            - name: CART_PERSISTENCE_PROVIDER
              value: postgres

            - name: CART_POSTGRES_HOST
              value: postgres

            - name: CART_POSTGRES_PORT
              value: "5432"

            - name: CART_POSTGRES_DB
              value: cartdb

            - name: CART_POSTGRES_USER
              value: retail_user

            - name: CART_POSTGRES_PASSWORD
              value: retailpassword

            - name: PORT
              value: "8080"

          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10