apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  namespace: retailstore
spec:
  replicas: 1

  selector:
    matchLabels:
      app: orders

  template:
    metadata:
      labels:
        app: orders

    spec:
      containers:
        - name: orders

          image: TODO : REEEMPLAZAR POR IMAGEN/orders:latest

          ports:
            - containerPort: 8080

          env:
            - name: GIN_MODE
              value: release

            - name: RETAIL_ORDERS_PERSISTENCE_ENDPOINT
              value: postgres:5432

            - name: RETAIL_ORDERS_PERSISTENCE_NAME
              value: orders

            - name: RETAIL_ORDERS_PERSISTENCE_USERNAME
              value: retail_user

            - name: RETAIL_ORDERS_PERSISTENCE_PASSWORD
              value: retailpassword

          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10