apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: retailstore
spec:
  replicas: 1

  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres

    spec:
      containers:
        - name: postgres
          image: postgres:16

          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_USER
              value: retail_user

            - name: POSTGRES_PASSWORD
              value: retailpassword

            - name: POSTGRES_DB
              value: orders

          volumeMounts:
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true

          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 30
            periodSeconds: 10

      volumes:
        - name: init-script
          configMap:
            name: postgres-init-script