apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: retailstore
spec:
  replicas: 1

  selector:
    matchLabels:
      app: ui

  template:
    metadata:
      labels:
        app: ui

    spec:
      containers:
        - name: ui

          image: TODO : REEEMPLAZAR POR IMAGEN/ui:latest

          ports:
            - containerPort: 8080

          env:
            - name: RETAIL_UI_ENDPOINTS_CATALOG
              value: http://catalog:8080

            - name: RETAIL_UI_ENDPOINTS_CARTS
              value: http://cart:8080

            - name: RETAIL_UI_ENDPOINTS_CHECKOUT
              value: http://checkout:8080

            - name: RETAIL_UI_ENDPOINTS_ORDERS
              value: http://orders:8080

          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10