name: App
on:
    push:
        branches: ["main", "develop"]
        paths:
            - 'src/admin/**'
    workflow_dispatch:
        inputs:
            environment:
                description: "Entorno a desplegar (develop/test/prod)"
                required: true
                default: "develop"
                type: choice
                options:
                    - develop
                    - test
                    - prod

jobs:
  terraform:
    name: Base de Actions
    runs-on: ubuntu-latest