name: pipeline-dispatcher - Invoke Service Pipeline

permissions:
  security-events: write
  contents: read
  id-token: write
  issues: write           
  pull-requests: write

on:
  push:
    branches:
      - main
      - develop
      - admin
      - cart
      - catalog
      - checkout
      - orders
      - ui
    paths: ['src/**', '.github/workflows/**']

  pull_request:
    branches: ["main", "develop"]
    paths: ['src/**', '.github/workflows/**']

  workflow_dispatch:
    inputs:
      service_name:
        description: 'Servicio específico (vacío = todos)'
        required: false
        type: choice
        options:
          - ""
          - admin
          - cart
          - catalog
          - checkout
          - orders
          - ui

      environment:
        description: 'Ambiente a desplegar'
        required: true
        type: choice
        options:
          - dev
          - test
          - prod


jobs:
  resolve-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          INPUT="${{ github.event.inputs.service_name }}"
          BRANCH="${GITHUB_REF#refs/heads/}"

          # Si hay input, solo ese servicio
          if [ -n "$INPUT" ]; then
            MATRIX=$(echo '[{"service_name":"'$INPUT'","service_path":"src/'$INPUT'"}]')

          # Si la rama coincide con un servicio, usar ese servicio
          elif [ "$BRANCH" = "admin" ] || [ "$BRANCH" = "cart" ] || [ "$BRANCH" = "catalog" ] || [ "$BRANCH" = "checkout" ] || [ "$BRANCH" = "orders" ] || [ "$BRANCH" = "ui" ]; then
            MATRIX=$(echo '[{"service_name":"'$BRANCH'","service_path":"src/'$BRANCH'"}]')

          else
            MATRIX='[
              {"service_name":"admin",    "service_path":"src/admin"},
              {"service_name":"cart",     "service_path":"src/cart"},
              {"service_name":"catalog",  "service_path":"src/catalog"},
              {"service_name":"checkout", "service_path":"src/checkout"},
              {"service_name":"orders",   "service_path":"src/orders"},
              {"service_name":"ui",       "service_path":"src/ui"}
            ]'
          fi

          # Compactar y exportar como output
          echo "matrix=$(echo $MATRIX | jq -c .)" >> $GITHUB_OUTPUT

  call-service:
    name: LLamar Pipeline de Servicio
    needs: resolve-matrix
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.resolve-matrix.outputs.matrix) }}

    uses: ./.github/workflows/services_pipeline.yml
    with:
      service_path: ${{ matrix.service_path }}
      service_name: ${{ matrix.service_name }}
    secrets: inherit

  configure-infra:
    name: Configurar Infraestructura
    runs-on: ubuntu-latest
    steps:
      - name: Verifica environment seleccionado
        run: |
          ENV="${{ inputs.environment }}"
          echo "Environment seleccionado: $ENV"

          case "$ENV" in
            dev|test|prod)
              echo "TFVARS_FILE=terraform/envs/${ENV}.tfvars" >> $GITHUB_ENV
              echo "Using tfvars: terraform/envs/${ENV}.tfvars"
              ;;
            *)
              echo "Invalid environment: $ENV. Debe ser dev, test o prod" >&2
              exit 1
              ;;
          esac

  call-infra:
    name: Pipeline de Infraestructura
    if: github.event_name == 'workflow_dispatch'
    needs: call-service
    uses: ./.github/workflows/infra_pipeline.yml
    with:
      environment: ${{ inputs.environment }}  
    secrets: inherit